---
- name: Load tasks specific to OS
  include_tasks: "setup-{{ distribution_id|join('-') }}.yml"
  when: distribution_id|first == 'Debian' and
        distribution_id|last in ['10', '11', 'NA', 'Testing', 'Unstable']
