---
# NOTE:
# - in Debian Stretch and later libpolarssl-dev has been renamed to libmbedtls-dev
# - list of packages that will be build by kdesrc-build: libkomparediff2-dev libgrantlee-dev
# - python-docutils is for rst2html command used by kdevelop for (better) documentation display
# - Debian Stretch packages libcv-dev, libcvaux-dev and libhighgui-dev have been replaced by libopencv-dev in Debian Sid
# - transitional package plasma-framework-dev (depends on libkf5plasma-dev) has been removed from sid
# - libkf5kface-dev depends on libkf5kface10.0.0 which in sid is build against old opencv packages that 
#   have already been removed from repository. Thus instead of depending on "libkf5.*-dev" we ignore
#   libkf5kface-dev by use of a posix regular expression.
# - libnm-glib-dev, libnm-glib-vpn-dev and libnm-util-dev are deprecated since network-manager 1.12.0-4

- include_role:
    name: jm1.virtual_pkg
  vars:
    package_name: "jm1-kdevelop-common"
    package_depends:
    # qt4
    #- qt4-demos
    #- qt4-designer
    - qt4-dev-tools
    #- qt4-doc
    - qt4-qmake
    - qt4-qmlviewer
    #- qt4-qtconfig
    #- libqt4-dev
    # qt5
    - qt5-qmake
    #- qt5-doc
    - qtcreator
    - 'libqt5.*-dev'
    - 'qt.*5-dev'
    - 'qt.*5-private-dev'
    - 'qt.*5-dev-tools'
    - 'python[0-9]?-pyqt5.[a-zA-Z0-9]*$'
    - pyqt5-dev
    - pyqt5-dev-tools
    - 'qt.*5-examples'
    - qt5-image-formats-plugins
    - qml
    # kde
    - konsole-kpart
    - kde-sc-dev-latest
    - okteta
    - breeze-icon-theme
    - breeze
    - oxygen-icon-theme
    - plasma-integration
    - konsole
    - kate
    - dolphin
    - systemsettings
    - plasma-framework
    - plasma-sdk
    - plasma-workspace-wayland
    - python-docutils
    - kde-l10n-de
    # misc
    - bison
    - flex
    - mesa-utils
    - heaptrack
    - heaptrack-gui

- when: not install_from_source
  block:
  - include_role:
      name: jm1.virtual_pkg
    vars:
      package_name: "jm1-kdevelop"
      package_depends:
      - jm1-kdevelop-common
      - kdevelop
      - clazy
      - kdevelop-php
      - kdevelop-python
      - plasma-kdevelop

- when: install_from_source
  block:
  - copy:
      src: "{{ distribution_id|join('-') }}/usr/local/src/kdesrc/"
      dest: /usr/local/src/kdesrc/
      mode: preserve
  
  - template:
      src: "{{ distribution_id|join('-') }}/usr/local/src/kdesrc/.kdesrc-buildrc.j2"
      dest: /usr/local/src/kdesrc/.kdesrc-buildrc
  
  - file:
      path: /usr/local/src/kdesrc/
      owner: nobody
      state: directory
      mode: "a+rx"
      recurse: yes
  
  - include_role:
      name: jm1.virtual_pkg
    vars:
      package_name: "jm1-kdevelop-build-deps"
      package_depends:
      - jm1-kdevelop-common
      - libkchart-dev
      - libdwarf-dev
      - libsparsehash-dev
      - libzstd-dev
      - libbz2-dev
      - libxslt-dev
      - libxml2-dev
      - libgif-dev
      - libvlc-dev
      - libvlccore-dev
      - libxapian-dev
      - fontforge
      - libgcrypt20-dev
      - libattr1-dev
      - network-manager-dev
      - libgtk-3-dev
      - xsltproc
      - xserver-xorg-dev
      - xserver-xorg-input-synaptics-dev
      - libpwquality-dev
      - modemmanager-dev
      - libxcb-keysyms1-dev
      - libepoxy-dev
      - libpolkit-agent-1-dev
      - libegl1-mesa-dev
      - libxcb-xkb-dev
      - libwww-perl
      - libxml-parser-perl
      - libjson-perl
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libarchive-dev
      - liblmdb-dev
      - libsvn-dev
      - libnm-dev
      #- 'libkf5([^k]+|(k([^f]|$)|kf([^a]|$)|kfa([^c]|$)|kfac([^e]|$)))+.*dev' 
      - 'libkf5.*dev' 
      - plasma-workspace-dev
      - okteta-dev
      - kdoctools-dev
      - libgrantlee5-dev
      - libkomparediff2-dev

  # # Workarounds
  # [ ! -d ~/.local/share/kservicetypes5/ ] && { 
  #     mkdir -p ~/.local/share/kservicetypes5/ && \
  #     ln -s /usr/share/kservicetypes5/plasma-dataengine.desktop ~/.local/share/kservicetypes5/plasma-dataengine.desktop;
  # }
  # ln -s /usr/share/kf5/ ~/.local/share/kf5

  - name: Build KDevelop from source
    # References:
    #  http://kfunk.org/2016/02/16/building-kdevelop-5-from-source-on-ubuntu-15-10/
    #  https://community.kde.org/Guidelines_and_HOWTOs/Build_from_source
    shell: |
      set -e
      cd /usr/local/src/kdesrc/
      
      # kdesrc-build must be able to find system-provided kde files or else kdevelop build fails with errors like:
      #  FAILED: app/plasma/dataengine/plasma-dataengine-kdevelopsessions.json 
      #  cd /usr/local/src/kdesrc/kdevelop/app/plasma/dataengine && /usr/bin/desktoptojson -i plasma-dataengine-kdevelopsessions.desktop -o /usr/local/src/kdesrc/build/kdevelop/app/plasma/dataengine/plasma-dataengine-kdevelopsessions.json -s plasma-dataengine.desktop
      #  Warning: Could not locate service type file kservicetypes5/plasma-dataengine.desktop, tried ("/usr/local/src/kdesrc/.local/share", "/usr/local/share") and ":/kservicetypes5/plasma-dataengine.desktop" ((null):0, (null))
      #  About to parse service type file "plasma-dataengine.desktop"
      #
      # NOTE: Another reason for this error message might be issue #208, which
      #       is solved since Docker 18.04 and libseccomp-2.3.3 [1][2].
      #       Ref.:
      #        [1] https://github.com/docker/for-linux/issues/208
      #        [2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901062
      if [ ! -e .local ]; then
          mkdir .local
          ln -s /usr/share .local/share
      fi
      
      if [ ! -e kdesrc-build ]; then
          git clone --depth 1 kde:kdesrc-build
          ln -s /usr/local/src/kdesrc/kdesrc-build/kdesrc-build /usr/local/bin/
      else
          (cd kdesrc-build && git pull)
      fi
      
      anything_changed=no
      
      # kdev-valgrind is not build here because it does not provide version-targeted branches 
      # for newer releases than 5.1 (highly outdated), which breaks compatibility to older
      # kdevelop/kdevplatform APIs once kdev-valgrind is updated, e.g. commit 3435f36 no
      # longer compiles with kdevplatform 5.3 and thus requires an update of kdevelop.
      
      for module in clazy kdevelop-pg-qt kdevelop kdev-php kdev-python; do
          if [ -f "build/$module/install_manifest.txt" ] &&
              cat "build/$module/install_manifest.txt" | xargs -i test -e '{}'; then
              echo "Skipping already installed $module.."
              continue
          fi
          anything_changed=yes
          sudo -u nobody HOME="$HOME" kdesrc-build --debug --no-install "$module"
          (cd build/$module && ninja install)
      done
      
      if [ "$anything_changed" = "no" ]; then
          echo "KDevelop is already installed. Skipping.." >&2
          exit 124
      fi
    environment:
      HOME: /usr/local/src/kdesrc/
    register: install_result
    changed_when:
      not (install_result.rc == 124 and install_result.stderr == "KDevelop is already installed. Skipping..")
    failed_when:
      not (
        (install_result.rc == 0) or
        (install_result.rc == 124 and install_result.stderr == "KDevelop is already installed. Skipping..")
      )

- set_fact:
    install_result: !!null
