---
- set_fact:
    apt_packages_common: "{{ __apt_packages_common|list }}"
  when: apt_packages_common|default(None) == None

- set_fact:
    apt_packages_build_deps: "{{ __apt_packages_build_deps|list }}"
  when: apt_packages_build_deps|default(None) == None

- set_fact:
    apt_packages_kdevelop: "{{ __apt_packages_kdevelop|list }}"
  when: apt_packages_kdevelop|default(None) == None

- set_fact:
    install_prefix: "{{ __install_prefix }}"
  when: install_prefix|default(None) == None

- set_fact:
    install_from_source: "{{ __install_from_source }}"
  when: install_from_source|default(None) == None

- name: Cleanup role default variables
  set_fact:
    __apt_packages_common: !!null
    __apt_packages_build_deps: !!null
    __apt_packages_kdevelop: !!null
    __install_prefix: !!null
    __install_from_source: !!null

- when: not install_from_source
  block:
  - include_role:
      name: jm1.virtual_pkg
    vars:
       package_name: "jm1-kdevelop"
       package_depends: "{{ apt_packages_common + apt_packages_kdevelop }}"

- when: install_from_source
  block:
  - copy:
      src: "{{ ansible_distribution }}-{{ ansible_distribution_version }}/usr/local/src/kdesrc/"
      dest: /usr/local/src/kdesrc/
      mode: preserve
  
  - template:
      src: "{{ ansible_distribution }}-{{ ansible_distribution_version }}/usr/local/src/kdesrc/.kdesrc-buildrc.j2"
      dest: /usr/local/src/kdesrc/.kdesrc-buildrc
  
  - file:
      path: /usr/local/src/kdesrc/
      owner: nobody
      state: directory
      mode: "a+rx"
      recurse: yes
  
  - include_role:
      name: jm1.virtual_pkg
    vars:
       package_name: "jm1-kdevelop"
       package_depends: "{{ apt_packages_common + apt_packages_build_deps }}"
  
  # # Workarounds
  # [ ! -d ~/.local/share/kservicetypes5/ ] && { 
  #     mkdir -p ~/.local/share/kservicetypes5/ && \
  #     ln -s /usr/share/kservicetypes5/plasma-dataengine.desktop ~/.local/share/kservicetypes5/plasma-dataengine.desktop;
  # }
  # ln -s /usr/share/kf5/ ~/.local/share/kf5
  
  - name: Build KDevelop from source
    # References:
    #  http://kfunk.org/2016/02/16/building-kdevelop-5-from-source-on-ubuntu-15-10/
    #  https://community.kde.org/Guidelines_and_HOWTOs/Build_from_source
    shell: |
      set -e
      cd /usr/local/src/kdesrc/
      
      # kdesrc-build must be able to find system-provided kde files or else kdevelop build fails with errors like:
      #  FAILED: app/plasma/dataengine/plasma-dataengine-kdevelopsessions.json 
      #  cd /usr/local/src/kdesrc/kdevelop/app/plasma/dataengine && /usr/bin/desktoptojson -i plasma-dataengine-kdevelopsessions.desktop -o /usr/local/src/kdesrc/build/kdevelop/app/plasma/dataengine/plasma-dataengine-kdevelopsessions.json -s plasma-dataengine.desktop
      #  Warning: Could not locate service type file kservicetypes5/plasma-dataengine.desktop, tried ("/usr/local/src/kdesrc/.local/share", "/usr/local/share") and ":/kservicetypes5/plasma-dataengine.desktop" ((null):0, (null))
      #  About to parse service type file "plasma-dataengine.desktop"
      #
      # NOTE: Another reason for this error message might be issue #208, which
      #       is solved since Docker 18.04 and libseccomp-2.3.3 [1][2].
      #       Ref.:
      #        [1] https://github.com/docker/for-linux/issues/208
      #        [2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901062
      if [ ! -e .local ]; then
          mkdir .local
          ln -s /usr/share .local/share
      fi
      
      if [ ! -e kdesrc-build ]; then
          git clone --depth 1 kde:kdesrc-build
          ln -s /usr/local/src/kdesrc/kdesrc-build/kdesrc-build /usr/local/bin/
      else
          (cd kdesrc-build && git pull)
      fi
      
      anything_changed=no
      
      # kdev-valgrind is not build here because it does not provide version-targeted branches 
      # for newer releases than 5.1 (highly outdated), which breaks compatibility to older
      # kdevelop/kdevplatform APIs once kdev-valgrind is updated, e.g. commit 3435f36 no
      # longer compiles with kdevplatform 5.3 and thus requires an update of kdevelop.
      
      for module in clazy kdevelop-pg-qt kdevelop kdev-php kdev-python; do
          if [ -f "build/$module/install_manifest.txt" ] &&
              cat "build/$module/install_manifest.txt" | xargs -i test -e '{}'; then
              echo "Skipping already installed $module.."
              continue
          fi
          anything_changed=yes
          sudo -u nobody HOME="$HOME" kdesrc-build --debug --no-install "$module"
          (cd build/$module && ninja install)
      done
      
      if [ "$anything_changed" = "no" ]; then
          echo "KDevelop is already installed. Skipping.." >&2
          exit 124
      fi
    environment:
      HOME: /usr/local/src/kdesrc/
    register: install_result
    changed_when:
      not (install_result.rc == 124 and install_result.stderr == "KDevelop is already installed. Skipping..")
    failed_when:
      not (
        (install_result.rc == 0) or
        (install_result.rc == 124 and install_result.stderr == "KDevelop is already installed. Skipping..")
      )

- set_fact:
    apt_packages_common: !!null
    apt_packages_build_deps: !!null
    apt_packages_kdevelop: !!null
    install_prefix: !!null
    install_from_source: !!null
    install_result: !!null
